apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myadmin
  name: myadmin
  namespace: db
spec:
  selector:
    matchLabels:
      app: myadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: myadmin
    spec:
      containers:
        - image: phpmyadmin/phpmyadmin
          imagePullPolicy: Always
          name: phpmyadmin
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            - name: PMA_ARBITRARY
              value: '1'

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: myadmin
  name: myadmin
  namespace: db
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: myadmin
  type: LoadBalancer