apiVersion: v1
kind: Namespace
metadata:
  name: bdd

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-bdd
  namespace: bdd
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi