apiVersion: v1
kind: Namespace
metadata:
  name: namespace-db

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-db
  namespace: namespace-db
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
