apiVersion: v1
kind: Namespace
metadata:
  name: namespace1

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota1
  namespace: namespace1
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi